#!/bin/sh
exec jq '
{
  "module": [
      .regions
    | .[]
		| select((.disable? // false) == false)
		| {
      ("aws_region_" + .region): {
        "source": "./modules/aws_region",
        "providers": {
          "aws": ("aws." + .region)
        },
        "region": .region,
        "domain": "${var.domain}",
        "cidr_block": (
          "${cidrsubnet(var.cidr_block, 5, " + (.id | tostring) + ")}"
        )
      }
    }
  ]
}'
