#!/bin/sh
exec jq '
{
  "provider": [
      .regions
    | .[]
    | select((.disable? // false) == false)
    | .region
    | {
         "aws": {
           "version": "~> 2.0",
           "region": .,
           "alias": .
        }
     }
  ]
}'
